services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - student-dashboard-network
    command: >
      sh -c "sleep 10 && php artisan storage:link --relative &&
             php artisan config:clear &&
             php artisan cache:clear &&
             php artisan migrate &&
             php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - type: bind
        source: .
        target: /var/www/html

      - type: bind
        source: ./storage
        target: /var/www/html/storage

      - type: bind
        source: ./public/storage
        target: /var/www/html/public/storage
        
      - type: volume
        source: vendor_data
        target: /var/www/html/vendor


  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: student_dashboard
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - student-dashboard-network

  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     PMA_USER: root
  #     PMA_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: password
  #   depends_on:
  #     - mysql
  #   networks:
  #     - student-dashboard-network

volumes:
  mysql_data:
  vendor_data:

networks:
  student-dashboard-network:
    driver: bridge
